<?php

// Generated by GenAI\Container\Util\Dumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Container\Container.
// require this file, then call the Closure with your container.

return function (\GenAI\Container\Container $c) {
    $c->register('Demo\\ApiController', function (\GenAI\Container\Container $c) {
        return new \Demo\ApiController();
    });
    $c->register('Demo\\PageController', function (\GenAI\Container\Container $c) {
        return new \Demo\PageController();
    });
};
