<?php

// Generated by GenAI\Routing\Util\RouteDumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Routing\Router.
// require this file, then call the Closure with your router.

return function (\GenAI\Routing\Router $r) {
    $r->register('GET', '#^/api/users/(?P<id>[^/]+)$#', array('id'), 'Demo\\ApiController@user');
    $r->register('GET', '#^/api/ping$#', array(), 'Demo\\ApiController@ping');
    $r->register('POST', '#^/api/users$#', array(), 'Demo\\ApiController@create');
    $r->register('GET', '#^/hello/(?P<name>[^/]+)$#', array('name'), 'Demo\\PageController@hello');
    $r->register('GET', '#^/greet/(?P<name>[^/]+)$#', array('name'), 'Demo\\PageController@greet');
    $r->register('GET', '#^/about$#', array(), 'Demo\\PageController@about');
};
