<?php

// Generated by GenAI\Web\Processor\WebProcessor - do not edit by hand.

return array (
  'rest' => 
  array (
    'Demo\\ApiController' => true,
  ),
  'engine' => NULL,
  'args' => 
  array (
    'Demo\\ApiController@ping' => 
    array (
    ),
    'Demo\\ApiController@user' => 
    array (
      0 => 
      array (
        'source' => 'attribute',
        'name' => 'id',
      ),
    ),
    'Demo\\ApiController@create' => 
    array (
      0 => 
      array (
        'source' => 'request',
      ),
    ),
    'Demo\\PageController@hello' => 
    array (
      0 => 
      array (
        'source' => 'attribute',
        'name' => 'name',
      ),
      1 => 
      array (
        'source' => 'model',
      ),
    ),
    'Demo\\PageController@about' => 
    array (
    ),
    'Demo\\PageController@greet' => 
    array (
      0 => 
      array (
        'source' => 'attribute',
        'name' => 'name',
      ),
    ),
  ),
);
